// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "dbfartifactapi/models"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// MockDBMgtRepository is an autogenerated mock type for the DBMgtRepository type
type MockDBMgtRepository struct {
	mock.Mock
}

type MockDBMgtRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDBMgtRepository) EXPECT() *MockDBMgtRepository_Expecter {
	return &MockDBMgtRepository_Expecter{mock: &_m.Mock}
}

// CountByCntIdAndDBNameAndDBType provides a mock function with given fields: tx, cntId, dbName, dbType
func (_m *MockDBMgtRepository) CountByCntIdAndDBNameAndDBType(tx *gorm.DB, cntId uint, dbName string, dbType string) (int64, error) {
	ret := _m.Called(tx, cntId, dbName, dbType)

	if len(ret) == 0 {
		panic("no return value specified for CountByCntIdAndDBNameAndDBType")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint, string, string) (int64, error)); ok {
		return rf(tx, cntId, dbName, dbType)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint, string, string) int64); ok {
		r0 = rf(tx, cntId, dbName, dbType)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, uint, string, string) error); ok {
		r1 = rf(tx, cntId, dbName, dbType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDBMgtRepository_CountByCntIdAndDBNameAndDBType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByCntIdAndDBNameAndDBType'
type MockDBMgtRepository_CountByCntIdAndDBNameAndDBType_Call struct {
	*mock.Call
}

// CountByCntIdAndDBNameAndDBType is a helper method to define mock.On call
//   - tx *gorm.DB
//   - cntId uint
//   - dbName string
//   - dbType string
func (_e *MockDBMgtRepository_Expecter) CountByCntIdAndDBNameAndDBType(tx interface{}, cntId interface{}, dbName interface{}, dbType interface{}) *MockDBMgtRepository_CountByCntIdAndDBNameAndDBType_Call {
	return &MockDBMgtRepository_CountByCntIdAndDBNameAndDBType_Call{Call: _e.mock.On("CountByCntIdAndDBNameAndDBType", tx, cntId, dbName, dbType)}
}

func (_c *MockDBMgtRepository_CountByCntIdAndDBNameAndDBType_Call) Run(run func(tx *gorm.DB, cntId uint, dbName string, dbType string)) *MockDBMgtRepository_CountByCntIdAndDBNameAndDBType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(uint), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockDBMgtRepository_CountByCntIdAndDBNameAndDBType_Call) Return(_a0 int64, _a1 error) *MockDBMgtRepository_CountByCntIdAndDBNameAndDBType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDBMgtRepository_CountByCntIdAndDBNameAndDBType_Call) RunAndReturn(run func(*gorm.DB, uint, string, string) (int64, error)) *MockDBMgtRepository_CountByCntIdAndDBNameAndDBType_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByCntIDAndDBType provides a mock function with given fields: tx, cntID, dbType
func (_m *MockDBMgtRepository) GetAllByCntIDAndDBType(tx *gorm.DB, cntID uint, dbType string) ([]*models.DBMgt, error) {
	ret := _m.Called(tx, cntID, dbType)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByCntIDAndDBType")
	}

	var r0 []*models.DBMgt
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint, string) ([]*models.DBMgt, error)); ok {
		return rf(tx, cntID, dbType)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint, string) []*models.DBMgt); ok {
		r0 = rf(tx, cntID, dbType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.DBMgt)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, uint, string) error); ok {
		r1 = rf(tx, cntID, dbType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDBMgtRepository_GetAllByCntIDAndDBType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByCntIDAndDBType'
type MockDBMgtRepository_GetAllByCntIDAndDBType_Call struct {
	*mock.Call
}

// GetAllByCntIDAndDBType is a helper method to define mock.On call
//   - tx *gorm.DB
//   - cntID uint
//   - dbType string
func (_e *MockDBMgtRepository_Expecter) GetAllByCntIDAndDBType(tx interface{}, cntID interface{}, dbType interface{}) *MockDBMgtRepository_GetAllByCntIDAndDBType_Call {
	return &MockDBMgtRepository_GetAllByCntIDAndDBType_Call{Call: _e.mock.On("GetAllByCntIDAndDBType", tx, cntID, dbType)}
}

func (_c *MockDBMgtRepository_GetAllByCntIDAndDBType_Call) Run(run func(tx *gorm.DB, cntID uint, dbType string)) *MockDBMgtRepository_GetAllByCntIDAndDBType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(uint), args[2].(string))
	})
	return _c
}

func (_c *MockDBMgtRepository_GetAllByCntIDAndDBType_Call) Return(_a0 []*models.DBMgt, _a1 error) *MockDBMgtRepository_GetAllByCntIDAndDBType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDBMgtRepository_GetAllByCntIDAndDBType_Call) RunAndReturn(run func(*gorm.DB, uint, string) ([]*models.DBMgt, error)) *MockDBMgtRepository_GetAllByCntIDAndDBType_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCntMgtId provides a mock function with given fields: tx, id
func (_m *MockDBMgtRepository) GetByCntMgtId(tx *gorm.DB, id uint) ([]models.DBMgt, error) {
	ret := _m.Called(tx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByCntMgtId")
	}

	var r0 []models.DBMgt
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint) ([]models.DBMgt, error)); ok {
		return rf(tx, id)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint) []models.DBMgt); ok {
		r0 = rf(tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.DBMgt)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, uint) error); ok {
		r1 = rf(tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDBMgtRepository_GetByCntMgtId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCntMgtId'
type MockDBMgtRepository_GetByCntMgtId_Call struct {
	*mock.Call
}

// GetByCntMgtId is a helper method to define mock.On call
//   - tx *gorm.DB
//   - id uint
func (_e *MockDBMgtRepository_Expecter) GetByCntMgtId(tx interface{}, id interface{}) *MockDBMgtRepository_GetByCntMgtId_Call {
	return &MockDBMgtRepository_GetByCntMgtId_Call{Call: _e.mock.On("GetByCntMgtId", tx, id)}
}

func (_c *MockDBMgtRepository_GetByCntMgtId_Call) Run(run func(tx *gorm.DB, id uint)) *MockDBMgtRepository_GetByCntMgtId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(uint))
	})
	return _c
}

func (_c *MockDBMgtRepository_GetByCntMgtId_Call) Return(_a0 []models.DBMgt, _a1 error) *MockDBMgtRepository_GetByCntMgtId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDBMgtRepository_GetByCntMgtId_Call) RunAndReturn(run func(*gorm.DB, uint) ([]models.DBMgt, error)) *MockDBMgtRepository_GetByCntMgtId_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: tx, id
func (_m *MockDBMgtRepository) GetByID(tx *gorm.DB, id uint) (*models.DBMgt, error) {
	ret := _m.Called(tx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.DBMgt
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint) (*models.DBMgt, error)); ok {
		return rf(tx, id)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint) *models.DBMgt); ok {
		r0 = rf(tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.DBMgt)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, uint) error); ok {
		r1 = rf(tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDBMgtRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockDBMgtRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - tx *gorm.DB
//   - id uint
func (_e *MockDBMgtRepository_Expecter) GetByID(tx interface{}, id interface{}) *MockDBMgtRepository_GetByID_Call {
	return &MockDBMgtRepository_GetByID_Call{Call: _e.mock.On("GetByID", tx, id)}
}

func (_c *MockDBMgtRepository_GetByID_Call) Run(run func(tx *gorm.DB, id uint)) *MockDBMgtRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(uint))
	})
	return _c
}

func (_c *MockDBMgtRepository_GetByID_Call) Return(_a0 *models.DBMgt, _a1 error) *MockDBMgtRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDBMgtRepository_GetByID_Call) RunAndReturn(run func(*gorm.DB, uint) (*models.DBMgt, error)) *MockDBMgtRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIds provides a mock function with given fields: tx, ids
func (_m *MockDBMgtRepository) GetByIds(tx *gorm.DB, ids []uint) ([]models.DBMgt, error) {
	ret := _m.Called(tx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetByIds")
	}

	var r0 []models.DBMgt
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, []uint) ([]models.DBMgt, error)); ok {
		return rf(tx, ids)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, []uint) []models.DBMgt); ok {
		r0 = rf(tx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.DBMgt)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, []uint) error); ok {
		r1 = rf(tx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDBMgtRepository_GetByIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIds'
type MockDBMgtRepository_GetByIds_Call struct {
	*mock.Call
}

// GetByIds is a helper method to define mock.On call
//   - tx *gorm.DB
//   - ids []uint
func (_e *MockDBMgtRepository_Expecter) GetByIds(tx interface{}, ids interface{}) *MockDBMgtRepository_GetByIds_Call {
	return &MockDBMgtRepository_GetByIds_Call{Call: _e.mock.On("GetByIds", tx, ids)}
}

func (_c *MockDBMgtRepository_GetByIds_Call) Run(run func(tx *gorm.DB, ids []uint)) *MockDBMgtRepository_GetByIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].([]uint))
	})
	return _c
}

func (_c *MockDBMgtRepository_GetByIds_Call) Return(_a0 []models.DBMgt, _a1 error) *MockDBMgtRepository_GetByIds_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDBMgtRepository_GetByIds_Call) RunAndReturn(run func(*gorm.DB, []uint) ([]models.DBMgt, error)) *MockDBMgtRepository_GetByIds_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDBMgtRepository creates a new instance of MockDBMgtRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDBMgtRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDBMgtRepository {
	mock := &MockDBMgtRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
