// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "dbfartifactapi/models"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// MockCntMgtRepository is an autogenerated mock type for the CntMgtRepository type
type MockCntMgtRepository struct {
	mock.Mock
}

type MockCntMgtRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCntMgtRepository) EXPECT() *MockCntMgtRepository_Expecter {
	return &MockCntMgtRepository_Expecter{mock: &_m.Mock}
}

// GetByDbmgts provides a mock function with given fields: tx, dbmgts
func (_m *MockCntMgtRepository) GetByDbmgts(tx *gorm.DB, dbmgts []uint) ([]models.CntMgt, error) {
	ret := _m.Called(tx, dbmgts)

	if len(ret) == 0 {
		panic("no return value specified for GetByDbmgts")
	}

	var r0 []models.CntMgt
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, []uint) ([]models.CntMgt, error)); ok {
		return rf(tx, dbmgts)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, []uint) []models.CntMgt); ok {
		r0 = rf(tx, dbmgts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.CntMgt)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, []uint) error); ok {
		r1 = rf(tx, dbmgts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCntMgtRepository_GetByDbmgts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByDbmgts'
type MockCntMgtRepository_GetByDbmgts_Call struct {
	*mock.Call
}

// GetByDbmgts is a helper method to define mock.On call
//   - tx *gorm.DB
//   - dbmgts []uint
func (_e *MockCntMgtRepository_Expecter) GetByDbmgts(tx interface{}, dbmgts interface{}) *MockCntMgtRepository_GetByDbmgts_Call {
	return &MockCntMgtRepository_GetByDbmgts_Call{Call: _e.mock.On("GetByDbmgts", tx, dbmgts)}
}

func (_c *MockCntMgtRepository_GetByDbmgts_Call) Run(run func(tx *gorm.DB, dbmgts []uint)) *MockCntMgtRepository_GetByDbmgts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].([]uint))
	})
	return _c
}

func (_c *MockCntMgtRepository_GetByDbmgts_Call) Return(_a0 []models.CntMgt, _a1 error) *MockCntMgtRepository_GetByDbmgts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCntMgtRepository_GetByDbmgts_Call) RunAndReturn(run func(*gorm.DB, []uint) ([]models.CntMgt, error)) *MockCntMgtRepository_GetByDbmgts_Call {
	_c.Call.Return(run)
	return _c
}

// GetCntMgtByDbMgtId provides a mock function with given fields: tx, dbmgtId
func (_m *MockCntMgtRepository) GetCntMgtByDbMgtId(tx *gorm.DB, dbmgtId uint) (*models.CntMgt, error) {
	ret := _m.Called(tx, dbmgtId)

	if len(ret) == 0 {
		panic("no return value specified for GetCntMgtByDbMgtId")
	}

	var r0 *models.CntMgt
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint) (*models.CntMgt, error)); ok {
		return rf(tx, dbmgtId)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint) *models.CntMgt); ok {
		r0 = rf(tx, dbmgtId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CntMgt)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, uint) error); ok {
		r1 = rf(tx, dbmgtId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCntMgtRepository_GetCntMgtByDbMgtId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCntMgtByDbMgtId'
type MockCntMgtRepository_GetCntMgtByDbMgtId_Call struct {
	*mock.Call
}

// GetCntMgtByDbMgtId is a helper method to define mock.On call
//   - tx *gorm.DB
//   - dbmgtId uint
func (_e *MockCntMgtRepository_Expecter) GetCntMgtByDbMgtId(tx interface{}, dbmgtId interface{}) *MockCntMgtRepository_GetCntMgtByDbMgtId_Call {
	return &MockCntMgtRepository_GetCntMgtByDbMgtId_Call{Call: _e.mock.On("GetCntMgtByDbMgtId", tx, dbmgtId)}
}

func (_c *MockCntMgtRepository_GetCntMgtByDbMgtId_Call) Run(run func(tx *gorm.DB, dbmgtId uint)) *MockCntMgtRepository_GetCntMgtByDbMgtId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(uint))
	})
	return _c
}

func (_c *MockCntMgtRepository_GetCntMgtByDbMgtId_Call) Return(_a0 *models.CntMgt, _a1 error) *MockCntMgtRepository_GetCntMgtByDbMgtId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCntMgtRepository_GetCntMgtByDbMgtId_Call) RunAndReturn(run func(*gorm.DB, uint) (*models.CntMgt, error)) *MockCntMgtRepository_GetCntMgtByDbMgtId_Call {
	_c.Call.Return(run)
	return _c
}

// GetCntMgtByID provides a mock function with given fields: tx, id
func (_m *MockCntMgtRepository) GetCntMgtByID(tx *gorm.DB, id uint) (*models.CntMgt, error) {
	ret := _m.Called(tx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCntMgtByID")
	}

	var r0 *models.CntMgt
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint) (*models.CntMgt, error)); ok {
		return rf(tx, id)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint) *models.CntMgt); ok {
		r0 = rf(tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CntMgt)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, uint) error); ok {
		r1 = rf(tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCntMgtRepository_GetCntMgtByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCntMgtByID'
type MockCntMgtRepository_GetCntMgtByID_Call struct {
	*mock.Call
}

// GetCntMgtByID is a helper method to define mock.On call
//   - tx *gorm.DB
//   - id uint
func (_e *MockCntMgtRepository_Expecter) GetCntMgtByID(tx interface{}, id interface{}) *MockCntMgtRepository_GetCntMgtByID_Call {
	return &MockCntMgtRepository_GetCntMgtByID_Call{Call: _e.mock.On("GetCntMgtByID", tx, id)}
}

func (_c *MockCntMgtRepository_GetCntMgtByID_Call) Run(run func(tx *gorm.DB, id uint)) *MockCntMgtRepository_GetCntMgtByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(uint))
	})
	return _c
}

func (_c *MockCntMgtRepository_GetCntMgtByID_Call) Return(_a0 *models.CntMgt, _a1 error) *MockCntMgtRepository_GetCntMgtByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCntMgtRepository_GetCntMgtByID_Call) RunAndReturn(run func(*gorm.DB, uint) (*models.CntMgt, error)) *MockCntMgtRepository_GetCntMgtByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: tx, id, status
func (_m *MockCntMgtRepository) UpdateStatus(tx *gorm.DB, id uint, status string) error {
	ret := _m.Called(tx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint, string) error); ok {
		r0 = rf(tx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCntMgtRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockCntMgtRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - tx *gorm.DB
//   - id uint
//   - status string
func (_e *MockCntMgtRepository_Expecter) UpdateStatus(tx interface{}, id interface{}, status interface{}) *MockCntMgtRepository_UpdateStatus_Call {
	return &MockCntMgtRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", tx, id, status)}
}

func (_c *MockCntMgtRepository_UpdateStatus_Call) Run(run func(tx *gorm.DB, id uint, status string)) *MockCntMgtRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(uint), args[2].(string))
	})
	return _c
}

func (_c *MockCntMgtRepository_UpdateStatus_Call) Return(_a0 error) *MockCntMgtRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCntMgtRepository_UpdateStatus_Call) RunAndReturn(run func(*gorm.DB, uint, string) error) *MockCntMgtRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCntMgtRepository creates a new instance of MockCntMgtRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCntMgtRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCntMgtRepository {
	mock := &MockCntMgtRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
