// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "dbfartifactapi/models"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// MockDBTypeRepository is an autogenerated mock type for the DBTypeRepository type
type MockDBTypeRepository struct {
	mock.Mock
}

type MockDBTypeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDBTypeRepository) EXPECT() *MockDBTypeRepository_Expecter {
	return &MockDBTypeRepository_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function with given fields: tx
func (_m *MockDBTypeRepository) GetAll(tx *gorm.DB) ([]models.DBType, error) {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.DBType
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB) ([]models.DBType, error)); ok {
		return rf(tx)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB) []models.DBType); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.DBType)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB) error); ok {
		r1 = rf(tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDBTypeRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockDBTypeRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockDBTypeRepository_Expecter) GetAll(tx interface{}) *MockDBTypeRepository_GetAll_Call {
	return &MockDBTypeRepository_GetAll_Call{Call: _e.mock.On("GetAll", tx)}
}

func (_c *MockDBTypeRepository_GetAll_Call) Run(run func(tx *gorm.DB)) *MockDBTypeRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB))
	})
	return _c
}

func (_c *MockDBTypeRepository_GetAll_Call) Return(_a0 []models.DBType, _a1 error) *MockDBTypeRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDBTypeRepository_GetAll_Call) RunAndReturn(run func(*gorm.DB) ([]models.DBType, error)) *MockDBTypeRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDBTypeRepository creates a new instance of MockDBTypeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDBTypeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDBTypeRepository {
	mock := &MockDBTypeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
