// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "dbfartifactapi/models"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// MockEndpointRepository is an autogenerated mock type for the EndpointRepository type
type MockEndpointRepository struct {
	mock.Mock
}

type MockEndpointRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEndpointRepository) EXPECT() *MockEndpointRepository_Expecter {
	return &MockEndpointRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: tx, id
func (_m *MockEndpointRepository) GetByID(tx *gorm.DB, id uint) (*models.Endpoint, error) {
	ret := _m.Called(tx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Endpoint
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint) (*models.Endpoint, error)); ok {
		return rf(tx, id)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint) *models.Endpoint); ok {
		r0 = rf(tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Endpoint)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, uint) error); ok {
		r1 = rf(tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEndpointRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockEndpointRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - tx *gorm.DB
//   - id uint
func (_e *MockEndpointRepository_Expecter) GetByID(tx interface{}, id interface{}) *MockEndpointRepository_GetByID_Call {
	return &MockEndpointRepository_GetByID_Call{Call: _e.mock.On("GetByID", tx, id)}
}

func (_c *MockEndpointRepository_GetByID_Call) Run(run func(tx *gorm.DB, id uint)) *MockEndpointRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(uint))
	})
	return _c
}

func (_c *MockEndpointRepository_GetByID_Call) Return(_a0 *models.Endpoint, _a1 error) *MockEndpointRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEndpointRepository_GetByID_Call) RunAndReturn(run func(*gorm.DB, uint) (*models.Endpoint, error)) *MockEndpointRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIds provides a mock function with given fields: tx, ids
func (_m *MockEndpointRepository) GetByIds(tx *gorm.DB, ids []uint) ([]models.Endpoint, error) {
	ret := _m.Called(tx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetByIds")
	}

	var r0 []models.Endpoint
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, []uint) ([]models.Endpoint, error)); ok {
		return rf(tx, ids)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, []uint) []models.Endpoint); ok {
		r0 = rf(tx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Endpoint)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, []uint) error); ok {
		r1 = rf(tx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEndpointRepository_GetByIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIds'
type MockEndpointRepository_GetByIds_Call struct {
	*mock.Call
}

// GetByIds is a helper method to define mock.On call
//   - tx *gorm.DB
//   - ids []uint
func (_e *MockEndpointRepository_Expecter) GetByIds(tx interface{}, ids interface{}) *MockEndpointRepository_GetByIds_Call {
	return &MockEndpointRepository_GetByIds_Call{Call: _e.mock.On("GetByIds", tx, ids)}
}

func (_c *MockEndpointRepository_GetByIds_Call) Run(run func(tx *gorm.DB, ids []uint)) *MockEndpointRepository_GetByIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].([]uint))
	})
	return _c
}

func (_c *MockEndpointRepository_GetByIds_Call) Return(_a0 []models.Endpoint, _a1 error) *MockEndpointRepository_GetByIds_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEndpointRepository_GetByIds_Call) RunAndReturn(run func(*gorm.DB, []uint) ([]models.Endpoint, error)) *MockEndpointRepository_GetByIds_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEndpointRepository creates a new instance of MockEndpointRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEndpointRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEndpointRepository {
	mock := &MockEndpointRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
