// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// MockBaseRepository is an autogenerated mock type for the BaseRepository type
type MockBaseRepository struct {
	mock.Mock
}

type MockBaseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBaseRepository) EXPECT() *MockBaseRepository_Expecter {
	return &MockBaseRepository_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function with no fields
func (_m *MockBaseRepository) Begin() *gorm.DB {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// MockBaseRepository_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockBaseRepository_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
func (_e *MockBaseRepository_Expecter) Begin() *MockBaseRepository_Begin_Call {
	return &MockBaseRepository_Begin_Call{Call: _e.mock.On("Begin")}
}

func (_c *MockBaseRepository_Begin_Call) Run(run func()) *MockBaseRepository_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBaseRepository_Begin_Call) Return(_a0 *gorm.DB) *MockBaseRepository_Begin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBaseRepository_Begin_Call) RunAndReturn(run func() *gorm.DB) *MockBaseRepository_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBaseRepository creates a new instance of MockBaseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBaseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBaseRepository {
	mock := &MockBaseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
